program FirstTry;         {Hur  na Turbo Vision!!!}
uses App;
var makaj:TApplication;
begin
  makaj.init; {konstruktor prevedie z kladn‚ nastavenia}
  makaj.run;  {met¢da zabezpecuje moznost ovl dat program uz¡vatelom}
  makaj.done; {destruktor ukonc¡ cinnost programu}
end.
   {Tento jednoduchy programcek m  pr zdne horn‚ menu, pracovn£ plochu}
   {so standardnym pozad¡m a stavovy riadok so zobrazenou hor£cou kl -}
   {vesou. }

   {BP kompendium od _140.pas}